# pdfbuilder.py
# Generates PDF files for /history and /escrow using ReportLab

from reportlab.platypus import (
    SimpleDocTemplate, 
    Table, 
    TableStyle, 
    Paragraph, 
    Spacer
)
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from io import BytesIO
from datetime import datetime, timedelta, timezone

from database import connect


# India time offset
IST_OFFSET = timedelta(hours=5, minutes=30)

def ist_format(dt_str):
    try:
        dt = datetime.fromisoformat(dt_str)
        dt = dt + IST_OFFSET
        return dt.strftime("%Y-%m-%d %I:%M %p")
    except:
        return dt_str


# ============================================================
# 🧾 GENERIC PDF BUILDER
# ============================================================

def build_pdf(data_rows, title, subtitle, filename_note):
    """
    Reusable PDF builder for all types of deal reports.
    """
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        rightMargin=25,
        leftMargin=25,
        topMargin=25,
        bottomMargin=25
    )

    story = []
    styles = getSampleStyleSheet()

    # Title
    story.append(Paragraph(f"<b>{title}</b>", styles["Title"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph(subtitle, styles["Heading4"]))
    story.append(Spacer(1, 12))

    # Table Headers
    table_data = [[
        "No.",
        "Buyer",
        "Seller",
        "Escrower",
        "Trade ID",
        "Amount",
        "Status",
        "Date"
    ]]

    # Add table rows
    for idx, row in enumerate(data_rows, start=1):
        table_data.append([
            str(idx),
            row["buyer_username"],
            row["seller_username"],
            row["created_by_username"],
            row["trade_id"],
            f"₹{row['amount']:.2f}",
            row["status"],
            ist_format(row["created_at"])
        ])

    # Table style
    table = Table(table_data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#222222")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F5F5")])
    ]))

    story.append(table)
    story.append(Spacer(1, 12))

    story.append(Paragraph(f"<i>{filename_note}</i>", styles["Normal"]))

    doc.build(story)

    pdf = buffer.getvalue()
    buffer.close()
    return pdf


# ============================================================
# 📜 /escrow — PDF of deals created by this user
# ============================================================

def build_escrow_pdf(user_id, uname):
    conn = connect()
    cur = conn.cursor()

    cur.execute("""
        SELECT buyer_username, seller_username, created_by_username,
               trade_id, amount, status, created_at
        FROM deals
        WHERE created_by=?
        ORDER BY id DESC
    """, (user_id,))

    deals = cur.fetchall()
    conn.close()

    title = "Era Escrow Bot — Escrow Summary"
    subtitle = f"All deals created by {uname}"
    note = f"Total Records: {len(deals)} — Generated by Era Escrow Bot"

    return build_pdf(deals, title, subtitle, note)


# ============================================================
# 📄 /history — PDF of ALL deals related to this user
# ============================================================

def build_history_pdf(user_id, uname):

    conn = connect()
    cur = conn.cursor()

    # username of this user
    cur.execute("SELECT username FROM users WHERE user_id=?", (user_id,))
    fetch = cur.fetchone()

    # fallback
    usertag = uname if not fetch else fetch["username"]

    cur.execute("""
        SELECT buyer_username, seller_username, created_by_username,
               trade_id, amount, status, created_at
        FROM deals
        WHERE buyer_username=? OR seller_username=? OR created_by=?
        ORDER BY id DESC
    """, (usertag, usertag, user_id))

    deals = cur.fetchall()
    conn.close()

    title = "Era Escrow Bot — Full Deal History"
    subtitle = f"Complete transaction history for {usertag}"
    note = f"Total Records: {len(deals)} — All-time history"

    return build_pdf(deals, title, subtitle, note)
