# utils.py
# Shared utility functions for all handlers

import sqlite3
from datetime import datetime, timezone, timedelta
from io import BytesIO

from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet


# ============================================================
# 🕒 TIME SETTINGS
# ============================================================

IST_OFFSET = timedelta(hours=5, minutes=30)


def ist_now():
    """Return current Indian time (IST)."""
    return datetime.now(timezone.utc) + IST_OFFSET


# ============================================================
# 👤 USERNAME FORMATTER
# ============================================================

def format_username(user):
    """Return @username or First Name or ID."""
    if getattr(user, "username", None):
        return f"@{user.username}"
    if getattr(user, "first_name", None):
        return user.first_name
    return str(user.id)


# ============================================================
# ━━━━━━━━━ DIVIDER
# ============================================================

def divider():
    return "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"


# ============================================================
# 🧹 Smart Reply (Reply + Auto-delete command)
# ============================================================

async def reply_and_clean(message, text, parse_mode="Markdown"):
    """Reply to a message and delete the command."""
    try:
        target = message.reply_to_message or message
        await target.reply_text(text, parse_mode=parse_mode)
        await message.delete()
    except:
        await message.reply_text(text, parse_mode=parse_mode)


# ============================================================
# ❓ Unknown Command Handler
# ============================================================

async def unknown_cmd_handler(update, context):
    """Handles any unknown /command"""
    await update.message.reply_text(
        "❓ Unknown command.\nUse /start to view available options.",
        parse_mode="Markdown"
    )


# ============================================================
# 📄 PDF Builder
# ============================================================

def build_pdf(rows, title="PDF Export"):
    """Generate styled PDF document from deal records."""
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        leftMargin=30,
        rightMargin=30,
        topMargin=30,
        bottomMargin=30,
    )

    styles = getSampleStyleSheet()
    story = []

    # Title
    story.append(Paragraph(f"<b>{title}</b>", styles["Title"]))
    story.append(Spacer(1, 12))

    if not rows:
        story.append(Paragraph("No records found.", styles["Normal"]))
        doc.build(story)
        pdf = buffer.getvalue()
        buffer.close()
        return pdf

    # Table headers
    columns = ["Trade ID", "Buyer", "Seller", "Amount", "Status", "Created"]

    table_data = [columns]

    for r in rows:
        table_data.append([
            r["trade_id"],
            r["buyer_username"],
            r["seller_username"],
            f"₹{float(r['amount']):.2f}",
            r["status"],
            r["created_at"].split("T")[0],
        ])

    # Create table
    table = Table(table_data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.black),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
    ]))

    story.append(table)
    story.append(Spacer(1, 12))
    story.append(Paragraph("<i>Generated by Era Escrow Bot</i>", styles["Italic"]))

    doc.build(story)
    pdf = buffer.getvalue()
    buffer.close()

    return pdf
